// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module CheckSum(	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  input          clock,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
                 reset,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  output         io_in_ready,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input          io_in_valid,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [511:0] io_in_bits_data,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_len,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_tcp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_tcp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [31:0]  io_in_bits_tcp_head_seq_num,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [3:0]   io_in_bits_ip_head_version,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_ihl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [5:0]   io_in_bits_ip_head_dscp,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [1:0]   io_in_bits_ip_head_ecn,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_ip_head_total_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_identification,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [2:0]   io_in_bits_ip_head_flags,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [12:0]  io_in_bits_ip_head_fragment_offset,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [7:0]   io_in_bits_ip_head_ttl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_protocol,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_ip_head_header_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [31:0]  io_in_bits_ip_head_src_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_dst_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [55:0]  io_in_bits_mac_head_preamble,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [7:0]   io_in_bits_mac_head_sfd,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [47:0]  io_in_bits_mac_head_dst_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_mac_head_src_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_mac_head_ethertype,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [31:0]  io_in_bits_mac_tail_crc_check,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output         io_out_valid,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [511:0] io_out_bits_data,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_len,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_tcp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_tcp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [31:0]  io_out_bits_tcp_head_seq_num,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_tcp_head_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [3:0]   io_out_bits_ip_head_version,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_ihl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [5:0]   io_out_bits_ip_head_dscp,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [1:0]   io_out_bits_ip_head_ecn,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_ip_head_total_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_identification,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [2:0]   io_out_bits_ip_head_flags,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [12:0]  io_out_bits_ip_head_fragment_offset,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [7:0]   io_out_bits_ip_head_ttl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_protocol,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_ip_head_header_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [31:0]  io_out_bits_ip_head_src_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_dst_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [55:0]  io_out_bits_mac_head_preamble,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [7:0]   io_out_bits_mac_head_sfd,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [47:0]  io_out_bits_mac_head_dst_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_mac_head_src_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_mac_head_ethertype,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [31:0]  io_out_bits_mac_tail_crc_check	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
);

  wire         io_out_valid_0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:14:16, :40:17]
  reg  [255:0] header_reg;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:17:28]
  wire [255:0] debug_header_reg = header_reg;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:17:28, :23:36]
  reg  [511:0] payload_reg;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:18:28]
  reg  [8:0]   header_words;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:19:28]
  reg  [8:0]   payload_words;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:20:28]
  reg  [16:0]  running_sum;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:32]
  wire [255:0] debug_payload_reg = payload_reg[255:0];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:18:28, :24:38]
  reg  [1:0]   state;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22]
  wire         _state_T_7 = state == 2'h1;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22, :33:34, :34:24]
  wire         _state_T_9 = state == 2'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22, :33:34, :35:24]
  reg  [1:0]   casez_tmp;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:33:34]
  always_comb begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:33:34]
    casez (state)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22, :33:34]
      2'b00:
        casez_tmp = {1'h0, io_in_valid};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:13:16, :33:34, :34:24]
      2'b01:
        casez_tmp = (|header_words) ? 2'h1 : 2'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:19:28, :33:34, :34:24, :35:{24,38}]
      2'b10:
        casez_tmp = {1'h1, ~(|payload_words)};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14, :20:28, :33:34, :36:{24,39}]
      default:
        casez_tmp = io_out_valid_0 ? 2'h0 : 2'h3;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:14:16, :30:22, :33:34, :36:24, :37:24, :40:17]
    endcase	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22, :33:34]
  end // always_comb
  wire         _GEN = state == 2'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22, :40:17]
  wire         _GEN_0 = _GEN | _state_T_7 | _state_T_9;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:12:15, :33:34, :40:17]
  assign io_out_valid_0 = ~_GEN_0 & (&state);	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:12:15, :14:16, :30:22, :33:34, :40:17]
  wire [9:0]   _payload_words_T = io_in_bits_len[9:0] + 10'h1;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:52:26, :66:37, :83:38]
  wire [16:0]  next = running_sum + {1'h0, header_reg[15:0]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:13:16, :17:28, :21:32, :78:{32,45}]
  wire [16:0]  next_1 = running_sum + {1'h0, payload_reg[15:0]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:13:16, :18:28, :21:32, :90:{32,46}]
  wire         _GEN_1 = _state_T_9 & (|payload_words);	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:20:28, :21:32, :33:34, :36:39, :40:17, :89:35, :91:21]
  always @(posedge clock) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    if (_GEN) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:40:17]
      if (io_in_valid) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
        header_reg <=
          {80'h6,
           io_in_bits_len + 16'h14,
           io_in_bits_tcp_head_src_port,
           io_in_bits_tcp_head_dst_port,
           io_in_bits_tcp_head_seq_num,
           96'h5000000000000000};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:17:28, :47:25, :52:26, :54:43, :57:28]
        payload_reg <=
          io_in_bits_len[0] ? {io_in_bits_data[503:0], 8'h0} : io_in_bits_data;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:18:28, :47:25, :62:{30,39}, :63:33]
        header_words <= 9'h10;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:19:28, :58:22]
        payload_words <= _payload_words_T[9:1];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:20:28, :66:{23,37,44}]
      end
    end
    else begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:40:17]
      if (_state_T_7 & (|header_words)) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:17:28, :19:28, :33:34, :35:38, :40:17, :77:34, :82:22]
        header_reg <= {16'h0, header_reg[255:16]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14, :17:28, :82:{22,36}]
        header_words <= header_words - 9'h1;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:19:28, :83:38]
      end
      if (_state_T_7 | ~_GEN_1) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:18:28, :20:28, :21:32, :33:34, :40:17, :89:35, :91:21]
      end
      else begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:20:28, :40:17]
        payload_reg <= {16'h0, payload_reg[511:16]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14, :18:28, :92:{23,38}]
        payload_words <= payload_words - 9'h1;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:20:28, :93:40]
      end
    end
    if (reset) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      running_sum <= 17'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:32]
      state <= 2'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22]
    end
    else begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      if (_GEN) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:40:17]
        if (io_in_valid)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
          running_sum <= 17'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:32]
      end
      else if (_state_T_7) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:33:34]
        if (|header_words)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:19:28, :35:38]
          running_sum <= next + {16'h0, next[16]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14, :21:32, :78:32, :80:{29,36}]
      end
      else if (_GEN_1)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:32, :40:17, :89:35, :91:21]
        running_sum <= next_1 + {16'h0, next_1[16]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14, :21:32, :90:32, :91:{29,36}]
      state <= casez_tmp;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:30:22, :33:34]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `FIRRTL_BEFORE_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:25];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    initial begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        `INIT_RANDOM_PROLOG_	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        for (logic [4:0] i = 5'h0; i < 5'h1A; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        end	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        header_reg =
          {_RANDOM[5'h0],
           _RANDOM[5'h1],
           _RANDOM[5'h2],
           _RANDOM[5'h3],
           _RANDOM[5'h4],
           _RANDOM[5'h5],
           _RANDOM[5'h6],
           _RANDOM[5'h7]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :17:28]
        payload_reg =
          {_RANDOM[5'h8],
           _RANDOM[5'h9],
           _RANDOM[5'hA],
           _RANDOM[5'hB],
           _RANDOM[5'hC],
           _RANDOM[5'hD],
           _RANDOM[5'hE],
           _RANDOM[5'hF],
           _RANDOM[5'h10],
           _RANDOM[5'h11],
           _RANDOM[5'h12],
           _RANDOM[5'h13],
           _RANDOM[5'h14],
           _RANDOM[5'h15],
           _RANDOM[5'h16],
           _RANDOM[5'h17]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :18:28]
        header_words = _RANDOM[5'h18][8:0];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :19:28]
        payload_words = _RANDOM[5'h18][17:9];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :19:28, :20:28]
        running_sum = {_RANDOM[5'h18][31:18], _RANDOM[5'h19][2:0]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :19:28, :21:32]
        state = _RANDOM[5'h19][4:3];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :21:32, :30:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `FIRRTL_AFTER_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = _GEN & ~io_in_valid;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :13:16, :40:17, :42:19, :43:25, :44:21]
  assign io_out_valid = io_out_valid_0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :14:16, :40:17]
  assign io_out_bits_data = io_in_bits_data;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_len = io_in_bits_len;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_src_port = io_in_bits_udp_head_src_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_dst_port = io_in_bits_udp_head_dst_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_length = io_in_bits_udp_head_length;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_checksum = io_in_bits_udp_head_checksum;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_src_port = io_in_bits_tcp_head_src_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_dst_port = io_in_bits_tcp_head_dst_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_seq_num = io_in_bits_tcp_head_seq_num;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_checksum =
    _GEN_0 | ~(&state) ? 16'h0 : ~(running_sum[15:0] + {15'h0, running_sum[16]});	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :6:14, :12:15, :21:32, :30:22, :33:34, :40:17, :99:{36,48,64}, :100:40]
  assign io_out_bits_ip_head_version = io_in_bits_ip_head_version;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_ihl = io_in_bits_ip_head_ihl;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_dscp = io_in_bits_ip_head_dscp;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_ecn = io_in_bits_ip_head_ecn;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_total_length = io_in_bits_ip_head_total_length;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_identification = io_in_bits_ip_head_identification;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_flags = io_in_bits_ip_head_flags;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_fragment_offset = io_in_bits_ip_head_fragment_offset;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_ttl = io_in_bits_ip_head_ttl;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_protocol = io_in_bits_ip_head_protocol;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_header_checksum = io_in_bits_ip_head_header_checksum;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_src_ip = io_in_bits_ip_head_src_ip;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_dst_ip = io_in_bits_ip_head_dst_ip;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_preamble = io_in_bits_mac_head_preamble;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_sfd = io_in_bits_mac_head_sfd;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_dst_mac = io_in_bits_mac_head_dst_mac;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_src_mac = io_in_bits_mac_head_src_mac;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_ethertype = io_in_bits_mac_head_ethertype;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_tail_crc_check = io_in_bits_mac_tail_crc_check;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
endmodule

