// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module CheckSum(	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  input          clock,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
                 reset,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  output         io_in_ready,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input          io_in_valid,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [511:0] io_in_bits_data,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_len,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_udp_head_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_tcp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_tcp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [31:0]  io_in_bits_tcp_head_seq_num,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [3:0]   io_in_bits_ip_head_version,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_ihl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [5:0]   io_in_bits_ip_head_dscp,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [1:0]   io_in_bits_ip_head_ecn,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_ip_head_total_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_identification,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [2:0]   io_in_bits_ip_head_flags,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [12:0]  io_in_bits_ip_head_fragment_offset,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [7:0]   io_in_bits_ip_head_ttl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_protocol,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_ip_head_header_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [31:0]  io_in_bits_ip_head_src_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_ip_head_dst_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [55:0]  io_in_bits_mac_head_preamble,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [7:0]   io_in_bits_mac_head_sfd,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [47:0]  io_in_bits_mac_head_dst_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_in_bits_mac_head_src_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [15:0]  io_in_bits_mac_head_ethertype,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  input  [31:0]  io_in_bits_mac_tail_crc_check,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [511:0] io_out_bits_data,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_len,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_udp_head_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_tcp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_tcp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [31:0]  io_out_bits_tcp_head_seq_num,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_tcp_head_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [3:0]   io_out_bits_ip_head_version,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_ihl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [5:0]   io_out_bits_ip_head_dscp,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [1:0]   io_out_bits_ip_head_ecn,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_ip_head_total_length,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_identification,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [2:0]   io_out_bits_ip_head_flags,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [12:0]  io_out_bits_ip_head_fragment_offset,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [7:0]   io_out_bits_ip_head_ttl,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_protocol,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_ip_head_header_checksum,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [31:0]  io_out_bits_ip_head_src_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_ip_head_dst_ip,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [55:0]  io_out_bits_mac_head_preamble,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [7:0]   io_out_bits_mac_head_sfd,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [47:0]  io_out_bits_mac_head_dst_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
                 io_out_bits_mac_head_src_mac,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [15:0]  io_out_bits_mac_head_ethertype,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
  output [31:0]  io_out_bits_mac_tail_crc_check	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
);

  reg  [775:0] latched_reg;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:15:24]
  reg  [16:0]  latched_length;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:16:31]
  reg  [16:0]  running_sum;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:18:28]
  reg  [1:0]   state;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:22]
  wire         _state_T_5 = state == 2'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:22, :23:34]
  wire         _state_T_7 = state == 2'h1;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:22, :23:34, :24:16]
  wire         _state_T_9 = state == 2'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:22, :23:34, :26:16]
  wire [15:0]  _payload_T = io_in_bits_len % 16'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:40:42]
  wire [15:0]  _tmp_latched_length_T_2 = io_in_bits_len + 16'h20;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:35:62]
  wire [15:0]  _latched_length_T = _tmp_latched_length_T_2 % 16'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:35:62, :40:42, :44:50]
  wire [16:0]  _next_sum_T_1 = running_sum + {1'h0, latched_reg[15:0]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:12:15, :15:24, :18:28, :53:{33,47}]
  wire         _GEN = _state_T_7 & (|latched_length);	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:16:31, :18:28, :23:34, :25:32, :29:17, :51:36, :54:21]
  always @(posedge clock) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    if (_state_T_5) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:23:34]
      if (io_in_valid)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
        latched_reg <=
          {80'h6,
           io_in_bits_len + 16'h14,
           io_in_bits_tcp_head_src_port,
           io_in_bits_tcp_head_dst_port,
           io_in_bits_tcp_head_seq_num,
           96'h5000000000000000,
           _payload_T[1:0] == 2'h0 ? {8'h0, io_in_bits_data} : {io_in_bits_data, 8'h0}};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:15:24, :21:22, :35:49, :38:{25,83}, :39:43, :40:{26,42,48}, :41:47, :43:27]
    end
    else if (_GEN)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:18:28, :29:17, :51:36, :54:21]
      latched_reg <= {16'h0, latched_reg[775:16]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14, :15:24, :56:{21,36}]
    if (reset) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      latched_length <= 17'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:16:31]
      running_sum <= 17'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:16:31, :18:28]
      state <= 2'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:22]
    end
    else begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      if (_state_T_5) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:23:34]
        if (io_in_valid) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14]
          latched_length <=
            {1'h0,
             _latched_length_T[1:0] == 2'h0
               ? _tmp_latched_length_T_2
               : io_in_bits_len + 16'h21};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:12:15, :16:31, :21:22, :35:62, :44:{24,30,50,56}, :46:54]
          running_sum <= 17'h0;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:16:31, :18:28]
        end
      end
      else if (_GEN) begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:18:28, :29:17, :51:36, :54:21]
        latched_length <= latched_length - 17'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:16:31, :55:42]
        running_sum <= {16'h0, _next_sum_T_1[16]} + {1'h0, _next_sum_T_1[15:0]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:6:14, :12:15, :18:28, :53:33, :54:{32,37,62}]
      end
      if (_state_T_9)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:23:34]
        state <= 2'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:21:22, :26:16]
      else if (_state_T_7)	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:23:34]
        state <= (|latched_length) ? 2'h1 : 2'h2;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:16:31, :21:22, :24:16, :25:{16,32}, :26:16]
      else	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:23:34]
        state <= {1'h0, _state_T_5 & io_in_valid};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:12:15, :21:22, :23:34, :24:16]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `FIRRTL_BEFORE_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:25];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    initial begin	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        `INIT_RANDOM_PROLOG_	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        for (logic [4:0] i = 5'h0; i < 5'h1A; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        end	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
        latched_reg =
          {_RANDOM[5'h0],
           _RANDOM[5'h1],
           _RANDOM[5'h2],
           _RANDOM[5'h3],
           _RANDOM[5'h4],
           _RANDOM[5'h5],
           _RANDOM[5'h6],
           _RANDOM[5'h7],
           _RANDOM[5'h8],
           _RANDOM[5'h9],
           _RANDOM[5'hA],
           _RANDOM[5'hB],
           _RANDOM[5'hC],
           _RANDOM[5'hD],
           _RANDOM[5'hE],
           _RANDOM[5'hF],
           _RANDOM[5'h10],
           _RANDOM[5'h11],
           _RANDOM[5'h12],
           _RANDOM[5'h13],
           _RANDOM[5'h14],
           _RANDOM[5'h15],
           _RANDOM[5'h16],
           _RANDOM[5'h17],
           _RANDOM[5'h18][7:0]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :15:24]
        latched_length = _RANDOM[5'h18][24:8];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :15:24, :16:31]
        running_sum = {_RANDOM[5'h18][31:25], _RANDOM[5'h19][9:0]};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :15:24, :18:28]
        state = _RANDOM[5'h19][11:10];	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :18:28, :21:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
      `FIRRTL_AFTER_INITIAL	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = _state_T_5 & ~io_in_valid;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :12:15, :23:34, :29:17, :32:19, :33:25, :34:21]
  assign io_out_bits_data = io_in_bits_data;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_len = io_in_bits_len;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_src_port = io_in_bits_udp_head_src_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_dst_port = io_in_bits_udp_head_dst_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_length = io_in_bits_udp_head_length;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_udp_head_checksum = io_in_bits_udp_head_checksum;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_src_port = io_in_bits_tcp_head_src_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_dst_port = io_in_bits_tcp_head_dst_port;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_seq_num = io_in_bits_tcp_head_seq_num;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_tcp_head_checksum =
    _state_T_5 | _state_T_7 | ~_state_T_9 ? 16'h0 : ~(running_sum[15:0]);	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7, :6:14, :11:15, :18:28, :23:34, :29:17, :60:{40,53}]
  assign io_out_bits_ip_head_version = io_in_bits_ip_head_version;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_ihl = io_in_bits_ip_head_ihl;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_dscp = io_in_bits_ip_head_dscp;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_ecn = io_in_bits_ip_head_ecn;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_total_length = io_in_bits_ip_head_total_length;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_identification = io_in_bits_ip_head_identification;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_flags = io_in_bits_ip_head_flags;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_fragment_offset = io_in_bits_ip_head_fragment_offset;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_ttl = io_in_bits_ip_head_ttl;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_protocol = io_in_bits_ip_head_protocol;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_header_checksum = io_in_bits_ip_head_header_checksum;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_src_ip = io_in_bits_ip_head_src_ip;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_ip_head_dst_ip = io_in_bits_ip_head_dst_ip;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_preamble = io_in_bits_mac_head_preamble;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_sfd = io_in_bits_mac_head_sfd;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_dst_mac = io_in_bits_mac_head_dst_mac;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_src_mac = io_in_bits_mac_head_src_mac;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_head_ethertype = io_in_bits_mac_head_ethertype;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
  assign io_out_bits_mac_tail_crc_check = io_in_bits_mac_tail_crc_check;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/CalcCheckSum.scala:5:7]
endmodule

