// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Tcp(	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7]
  input          clock,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7]
                 reset,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7]
  output         io_in_ready,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  input          io_in_valid,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  input  [511:0] io_in_bits_data,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  input  [15:0]  io_in_bits_len,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  input          io_out_ready,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  output         io_out_valid,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  output [511:0] io_out_bits_data,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  output [15:0]  io_out_bits_len,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
                 io_out_bits_tcp_head_src_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
                 io_out_bits_tcp_head_dst_port,	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
  output [31:0]  io_out_bits_tcp_head_seq_num	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:7:14]
);

  wire _lfsr3_prng_io_out_0;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_1;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_2;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_3;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_4;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_5;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_6;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_7;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_8;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_9;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_10;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_11;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_12;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_13;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_14;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr3_prng_io_out_15;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_0;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_1;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_2;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_3;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_4;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_5;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_6;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_7;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_8;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_9;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_10;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_11;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_12;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_13;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_14;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr2_prng_io_out_15;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_0;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_1;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_2;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_3;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_4;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_5;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_6;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_7;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_8;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_9;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_10;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_11;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_12;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_13;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_14;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire _lfsr1_prng_io_out_15;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  MaxPeriodFibonacciLFSR lfsr1_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock     (clock),
    .reset     (reset),
    .io_out_0  (_lfsr1_prng_io_out_0),
    .io_out_1  (_lfsr1_prng_io_out_1),
    .io_out_2  (_lfsr1_prng_io_out_2),
    .io_out_3  (_lfsr1_prng_io_out_3),
    .io_out_4  (_lfsr1_prng_io_out_4),
    .io_out_5  (_lfsr1_prng_io_out_5),
    .io_out_6  (_lfsr1_prng_io_out_6),
    .io_out_7  (_lfsr1_prng_io_out_7),
    .io_out_8  (_lfsr1_prng_io_out_8),
    .io_out_9  (_lfsr1_prng_io_out_9),
    .io_out_10 (_lfsr1_prng_io_out_10),
    .io_out_11 (_lfsr1_prng_io_out_11),
    .io_out_12 (_lfsr1_prng_io_out_12),
    .io_out_13 (_lfsr1_prng_io_out_13),
    .io_out_14 (_lfsr1_prng_io_out_14),
    .io_out_15 (_lfsr1_prng_io_out_15)
  );
  MaxPeriodFibonacciLFSR lfsr2_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock     (clock),
    .reset     (reset),
    .io_out_0  (_lfsr2_prng_io_out_0),
    .io_out_1  (_lfsr2_prng_io_out_1),
    .io_out_2  (_lfsr2_prng_io_out_2),
    .io_out_3  (_lfsr2_prng_io_out_3),
    .io_out_4  (_lfsr2_prng_io_out_4),
    .io_out_5  (_lfsr2_prng_io_out_5),
    .io_out_6  (_lfsr2_prng_io_out_6),
    .io_out_7  (_lfsr2_prng_io_out_7),
    .io_out_8  (_lfsr2_prng_io_out_8),
    .io_out_9  (_lfsr2_prng_io_out_9),
    .io_out_10 (_lfsr2_prng_io_out_10),
    .io_out_11 (_lfsr2_prng_io_out_11),
    .io_out_12 (_lfsr2_prng_io_out_12),
    .io_out_13 (_lfsr2_prng_io_out_13),
    .io_out_14 (_lfsr2_prng_io_out_14),
    .io_out_15 (_lfsr2_prng_io_out_15)
  );
  MaxPeriodFibonacciLFSR lfsr3_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock     (clock),
    .reset     (reset),
    .io_out_0  (_lfsr3_prng_io_out_0),
    .io_out_1  (_lfsr3_prng_io_out_1),
    .io_out_2  (_lfsr3_prng_io_out_2),
    .io_out_3  (_lfsr3_prng_io_out_3),
    .io_out_4  (_lfsr3_prng_io_out_4),
    .io_out_5  (_lfsr3_prng_io_out_5),
    .io_out_6  (_lfsr3_prng_io_out_6),
    .io_out_7  (_lfsr3_prng_io_out_7),
    .io_out_8  (_lfsr3_prng_io_out_8),
    .io_out_9  (_lfsr3_prng_io_out_9),
    .io_out_10 (_lfsr3_prng_io_out_10),
    .io_out_11 (_lfsr3_prng_io_out_11),
    .io_out_12 (_lfsr3_prng_io_out_12),
    .io_out_13 (_lfsr3_prng_io_out_13),
    .io_out_14 (_lfsr3_prng_io_out_14),
    .io_out_15 (_lfsr3_prng_io_out_15)
  );
  assign io_in_ready = ~io_in_valid | io_out_ready & io_in_valid;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7, :15:{18,31}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_out_valid = io_in_valid;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7]
  assign io_out_bits_data = io_in_bits_data;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7]
  assign io_out_bits_len = io_in_bits_len;	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7]
  assign io_out_bits_tcp_head_src_port =
    {_lfsr1_prng_io_out_15,
     _lfsr1_prng_io_out_14,
     _lfsr1_prng_io_out_13,
     _lfsr1_prng_io_out_12,
     _lfsr1_prng_io_out_11,
     _lfsr1_prng_io_out_10,
     _lfsr1_prng_io_out_9,
     _lfsr1_prng_io_out_8,
     _lfsr1_prng_io_out_7,
     _lfsr1_prng_io_out_6,
     _lfsr1_prng_io_out_5,
     _lfsr1_prng_io_out_4,
     _lfsr1_prng_io_out_3,
     _lfsr1_prng_io_out_2,
     _lfsr1_prng_io_out_1,
     _lfsr1_prng_io_out_0};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7, src/main/scala/chisel3/util/random/PRNG.scala:91:22, :95:17]
  assign io_out_bits_tcp_head_dst_port =
    {_lfsr2_prng_io_out_15,
     _lfsr2_prng_io_out_14,
     _lfsr2_prng_io_out_13,
     _lfsr2_prng_io_out_12,
     _lfsr2_prng_io_out_11,
     _lfsr2_prng_io_out_10,
     _lfsr2_prng_io_out_9,
     _lfsr2_prng_io_out_8,
     _lfsr2_prng_io_out_7,
     _lfsr2_prng_io_out_6,
     _lfsr2_prng_io_out_5,
     _lfsr2_prng_io_out_4,
     _lfsr2_prng_io_out_3,
     _lfsr2_prng_io_out_2,
     _lfsr2_prng_io_out_1,
     _lfsr2_prng_io_out_0};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7, src/main/scala/chisel3/util/random/PRNG.scala:91:22, :95:17]
  assign io_out_bits_tcp_head_seq_num =
    {16'h0,
     _lfsr3_prng_io_out_15,
     _lfsr3_prng_io_out_14,
     _lfsr3_prng_io_out_13,
     _lfsr3_prng_io_out_12,
     _lfsr3_prng_io_out_11,
     _lfsr3_prng_io_out_10,
     _lfsr3_prng_io_out_9,
     _lfsr3_prng_io_out_8,
     _lfsr3_prng_io_out_7,
     _lfsr3_prng_io_out_6,
     _lfsr3_prng_io_out_5,
     _lfsr3_prng_io_out_4,
     _lfsr3_prng_io_out_3,
     _lfsr3_prng_io_out_2,
     _lfsr3_prng_io_out_1,
     _lfsr3_prng_io_out_0};	// @[home/cao/tcpudp2mac/chisel-playground/playground/src/PipelineStage/Tcp.scala:6:7, :23:32, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
endmodule

